import { image } from "../constants/images";


export const contacts = [
    {
        id: '1',
        userName: 'John Doe',
        userImg: image.USER1,
        isOnline: false,
        lastSeen: '3 Days ago',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '2',
        userName: 'Marry Lio',
        userImg: image.USER2,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Good morning...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '3',
        userName: 'Lucia Mu',
        userImg: image.USER3,
        isOnline: false,
        lastSeen: '2 weeks ago',
        lastMessage: "What's up...",
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '4',
        userName: 'Raki Lili',
        userImg: image.USER4,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Send me the link',
        messageInQueue: 0,
        sentDate: 'Today',
    },
    {
        id: '5',
        userName: 'Raki Devine',
        userImg: image.USER5,
        isOnline: false,
        lastSeen: '5 days ago',
        lastMessage: 'We are doing...',
        messageInQueue: 0,
        sentDate: '23/9',
    },
    {
        id: '6',
        userName: 'Aris Yup',
        userImg: image.USER6,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: 'Today',
    },
    {
        id: '7',
        userName: 'Aris Yup',
        userImg: image.USER6,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '8',
        userName: 'Billy Di',
        userImg: image.USER7,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '9',
        userName: 'Aris Biu',
        userImg: image.USER8,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'How is it going...',
        messageInQueue: 3,
        sentDate: '12/7',
    },
]
